This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./tb_report.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file tb_report.acn....done (31 entries accepted, 0 rejected).
Sorting entries....done (189 comparisons).
Generating output file tb_report.acr....done (23 lines written, 0 warnings).
Output written in tb_report.acr.
Transcript written in tb_report.alg.
